"""
Linguistic Agent — Actuator AI

Responsibilities:
  - Real-time message translation
  - Customer sentiment analysis
  - Tone detection and adjustment recommendations
  - Language detection
  - Communication quality scoring
"""

import sys
import os
import asyncio
from datetime import datetime, timezone

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", ".."))

from agents import Agent, Runner, ModelSettings, function_tool

from shared.models.ollama_provider import get_model
from shared.mcp_config import create_mcp_postgres
from shared.guardrails.safety import detect_jailbreak


# --- Tools ---

@function_tool
def detect_language(text: str) -> str:
    """Detect the language of input text."""
    indicators = {
        "ur": ["کیا", "ہے", "میں", "اور", "سے"],
        "ar": ["هل", "في", "من", "على", "أن"],
        "zh": ["的", "是", "在", "了", "我"],
    }
    for lang, words in indicators.items():
        if any(w in text for w in words):
            lang_names = {"ur": "Urdu", "ar": "Arabic", "zh": "Chinese"}
            return f"Detected language: {lang_names[lang]} ({lang}) | Confidence: 0.92"
    return "Detected language: English (en) | Confidence: 0.95"


@function_tool
def translate_text(text: str, source_lang: str, target_lang: str) -> str:
    """Translate text between languages. Use ISO 639-1 codes."""
    return (
        f"Translation ({source_lang} → {target_lang}):\n"
        f"  Original: {text[:200]}\n"
        f"  Translated: [Translation would be generated by translation API]\n"
        f"  Note: For production, integrate DeepL or Google Translate API."
    )


@function_tool
def analyze_sentiment(text: str) -> str:
    """Analyze sentiment of customer message. Returns score and breakdown."""
    negative_words = ["angry", "frustrated", "terrible", "worst", "hate", "ridiculous", "unacceptable"]
    positive_words = ["great", "thanks", "excellent", "love", "amazing", "helpful", "perfect"]

    text_lower = text.lower()
    neg = sum(1 for w in negative_words if w in text_lower)
    pos = sum(1 for w in positive_words if w in text_lower)

    if neg > pos:
        score = max(-1.0, -0.3 * neg)
        label = "NEGATIVE"
        urgency = "HIGH" if neg >= 2 else "MEDIUM"
    elif pos > neg:
        score = min(1.0, 0.3 * pos)
        label = "POSITIVE"
        urgency = "LOW"
    else:
        score = 0.0
        label = "NEUTRAL"
        urgency = "LOW"

    return (
        f"Sentiment Analysis:\n"
        f"  Score: {score:.2f} (-1.0 to 1.0)\n"
        f"  Label: {label}\n"
        f"  Urgency: {urgency}\n"
        f"  Negative signals: {neg} | Positive signals: {pos}\n"
        f"  Recommendation: {'Prioritize — customer is upset' if label == 'NEGATIVE' else 'Standard handling'}"
    )


@function_tool
def assess_communication_quality(agent_response: str) -> str:
    """Score the quality of an agent's response for QA purposes."""
    length = len(agent_response)
    has_greeting = any(w in agent_response.lower() for w in ["hello", "hi", "dear"])
    has_empathy = any(w in agent_response.lower() for w in ["understand", "sorry", "appreciate", "apologize"])
    has_action = any(w in agent_response.lower() for w in ["will", "can", "let me", "i've"])
    has_closing = any(w in agent_response.lower() for w in ["anything else", "help you", "further"])

    score = 0
    breakdown = []
    if has_greeting:
        score += 20
        breakdown.append("✅ Professional greeting")
    else:
        breakdown.append("❌ Missing greeting")
    if has_empathy:
        score += 25
        breakdown.append("✅ Empathetic language")
    else:
        breakdown.append("❌ Missing empathy")
    if has_action:
        score += 30
        breakdown.append("✅ Action-oriented")
    else:
        breakdown.append("❌ No clear action items")
    if has_closing:
        score += 15
        breakdown.append("✅ Proper closing")
    else:
        breakdown.append("❌ Missing closing")
    if 100 < length < 2000:
        score += 10
        breakdown.append("✅ Appropriate length")
    else:
        breakdown.append("⚠ Length needs adjustment")

    return (
        f"Communication Quality Score: {score}/100\n"
        f"Breakdown:\n  " + "\n  ".join(breakdown)
    )


def build_instructions(ctx, agent):
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    customer_email = ctx.context.get("customer_email", "Unknown")
    return f"""You are the Linguistic Agent for Actuator AI. Current time: {now}
CURRENT USER: {customer_email}

DATABASE ACCESS: You have a 'query' MCP tool for direct PostgreSQL access if needed.
NEVER guess sentiment scores — base all analysis on the actual message text using your tools.

STEP-BY-STEP PROTOCOL:
1. For non-English messages: call detect_language first, then translate_text (ar/ur → en)
2. Always call analyze_sentiment on the customer message — report score, label, urgency
3. For QA requests: call assess_communication_quality with the agent response text
4. If sentiment is NEGATIVE and urgency is HIGH: flag explicitly for immediate escalation
5. Optionally query past feedback via MCP to establish customer NPS baseline:
   SELECT rating, nps_score, comment FROM feedback WHERE customer_id = (SELECT customer_id FROM customer_contacts WHERE email ILIKE '{customer_email}') ORDER BY created_at DESC LIMIT 1

AVAILABLE TOOLS: query (MCP), detect_language, translate_text, analyze_sentiment, assess_communication_quality

GUIDELINES:
- Be objective in sentiment scoring — don't inflate or deflate
- For translations, note any cultural nuances that may affect meaning
- Communication quality scores should be constructive, not punitive
- Support primary languages: English, Urdu, Arabic, Chinese, Spanish
- HIGH urgency negative sentiment → recommend immediate escalation"""


# --- Agent ---
agent = Agent(
    name="Linguistic Agent",
    instructions=build_instructions,
    model=get_model(),
    model_settings=ModelSettings(temperature=0.3, max_tokens=1000),
    tools=[
        detect_language,
        translate_text,
        analyze_sentiment,
        assess_communication_quality,
    ],
    input_guardrails=[detect_jailbreak],
    handoff_description="Language: translation, sentiment analysis, tone detection, communication QA, language detection",
)


async def main():
    queries = [
        "Analyze this customer message: 'This is RIDICULOUS! I've been waiting 3 weeks and nobody cares!'",
    ]
    for query in queries:
        print(f"\n{'='*60}\nQuery: {query}")
        result = await Runner.run(agent, query)
        print(f"Response:\n{result.final_output}")


if __name__ == "__main__":
    asyncio.run(main())
