"""
Linguistic Agent — Actuator AI

Responsibilities:
  - Real-time message translation
  - Customer sentiment analysis
  - Tone detection and adjustment recommendations
  - Language detection
  - Communication quality scoring
"""

import sys
import os
import asyncio
from datetime import datetime, timezone

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", ".."))

from agents import Agent, Runner, ModelSettings, function_tool

from shared.models.ollama_provider import get_model
from shared.guardrails.safety import detect_jailbreak


# --- Tools ---

@function_tool
def detect_language(text: str) -> str:
    """Detect the language of input text."""
    # Production: use langdetect or fasttext
    indicators = {
        "ur": ["کیا", "ہے", "میں", "اور", "سے"],
        "ar": ["هل", "في", "من", "على", "أن"],
        "zh": ["的", "是", "在", "了", "我"],
    }
    for lang, words in indicators.items():
        if any(w in text for w in words):
            lang_names = {"ur": "Urdu", "ar": "Arabic", "zh": "Chinese"}
            return f"Detected language: {lang_names[lang]} ({lang}) | Confidence: 0.92"
    return "Detected language: English (en) | Confidence: 0.95"


@function_tool
def translate_text(text: str, source_lang: str, target_lang: str) -> str:
    """Translate text between languages. Use ISO 639-1 codes."""
    # Production: integrate Google Translate API, DeepL, or local model
    return (
        f"Translation ({source_lang} → {target_lang}):\n"
        f"  Original: {text[:200]}\n"
        f"  Translated: [Translation would be generated by translation API]\n"
        f"  Note: For production, integrate DeepL or Google Translate API."
    )


@function_tool
def analyze_sentiment(text: str) -> str:
    """Analyze sentiment of customer message. Returns score and breakdown."""
    # Production: use fine-tuned model or API
    negative_words = ["angry", "frustrated", "terrible", "worst", "hate", "ridiculous", "unacceptable"]
    positive_words = ["great", "thanks", "excellent", "love", "amazing", "helpful", "perfect"]
    neutral_words = ["okay", "fine", "sure", "understood"]

    text_lower = text.lower()
    neg = sum(1 for w in negative_words if w in text_lower)
    pos = sum(1 for w in positive_words if w in text_lower)

    if neg > pos:
        score = max(-1.0, -0.3 * neg)
        label = "NEGATIVE"
        urgency = "HIGH" if neg >= 2 else "MEDIUM"
    elif pos > neg:
        score = min(1.0, 0.3 * pos)
        label = "POSITIVE"
        urgency = "LOW"
    else:
        score = 0.0
        label = "NEUTRAL"
        urgency = "LOW"

    return (
        f"Sentiment Analysis:\n"
        f"  Score: {score:.2f} (-1.0 to 1.0)\n"
        f"  Label: {label}\n"
        f"  Urgency: {urgency}\n"
        f"  Negative signals: {neg} | Positive signals: {pos}\n"
        f"  Recommendation: {'Prioritize — customer is upset' if label == 'NEGATIVE' else 'Standard handling'}"
    )


@function_tool
def assess_communication_quality(agent_response: str) -> str:
    """Score the quality of an agent's response for QA purposes."""
    length = len(agent_response)
    has_greeting = any(w in agent_response.lower() for w in ["hello", "hi", "dear"])
    has_empathy = any(w in agent_response.lower() for w in ["understand", "sorry", "appreciate", "apologize"])
    has_action = any(w in agent_response.lower() for w in ["will", "can", "let me", "i've"])
    has_closing = any(w in agent_response.lower() for w in ["anything else", "help you", "further"])

    score = 0
    breakdown = []
    if has_greeting:
        score += 20
        breakdown.append("✅ Professional greeting")
    else:
        breakdown.append("❌ Missing greeting")
    if has_empathy:
        score += 25
        breakdown.append("✅ Empathetic language")
    else:
        breakdown.append("❌ Missing empathy")
    if has_action:
        score += 30
        breakdown.append("✅ Action-oriented")
    else:
        breakdown.append("❌ No clear action items")
    if has_closing:
        score += 15
        breakdown.append("✅ Proper closing")
    else:
        breakdown.append("❌ Missing closing")
    if 100 < length < 2000:
        score += 10
        breakdown.append("✅ Appropriate length")
    else:
        breakdown.append("⚠ Length needs adjustment")

    return (
        f"Communication Quality Score: {score}/100\n"
        f"Breakdown:\n  " + "\n  ".join(breakdown)
    )


# --- Dynamic Instructions ---
def build_instructions(ctx, agent):
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    return f"""You are the Linguistic Agent for Actuator AI. Current time: {now}

CAPABILITIES:
- Language detection for incoming messages
- Text translation between supported languages
- Sentiment analysis with urgency scoring
- Communication quality assessment for agent responses
- Tone analysis and improvement suggestions

PROTOCOL:
1. For non-English messages: detect language first, then translate
2. For sentiment analysis: provide score, label, and actionable recommendation
3. For QA: assess communication quality and suggest improvements
4. Always preserve original meaning in translations
5. Flag high-urgency negative sentiment for immediate attention

GUIDELINES:
- Be objective in sentiment scoring — don't inflate or deflate
- For translations, note any cultural nuances that may affect meaning
- Communication quality scores should be constructive, not punitive
- Support primary languages: English, Urdu, Arabic, Chinese, Spanish"""


# --- Agent ---
agent = Agent(
    name="Linguistic Agent",
    instructions=build_instructions,
    model=get_model(),
    model_settings=ModelSettings(temperature=0.3, max_tokens=1000),
    tools=[
        detect_language,
        translate_text,
        analyze_sentiment,
        assess_communication_quality,
    ],
    input_guardrails=[detect_jailbreak],
    handoff_description="Language: translation, sentiment analysis, tone detection, communication QA, language detection",
)


async def main():
    queries = [
        "Analyze this customer message: 'This is RIDICULOUS! I've been waiting 3 weeks and nobody cares!'",
        # "Translate this to Urdu: 'Your account has been upgraded to Pro plan.'",
        # "Score this agent response: 'Balance is 5000. Anything else?'",
    ]
    for query in queries:
        print(f"\n{'='*60}\nQuery: {query}")
        result = await Runner.run(agent, query)
        print(f"Response:\n{result.final_output}")


if __name__ == "__main__":
    asyncio.run(main())
